/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContactReplyDto,
  ContactResponseDto,
  CreateContactDto,
} from "../../const";

import { customInstance } from "../../../shared/axios/lib/customInstance";
import type {
  ErrorType,
  BodyType,
} from "../../../shared/axios/lib/customInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 대출 문의 등록
 */
export const contactControllerCreate = (
  createContactDto: BodyType<CreateContactDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ContactResponseDto>(
    {
      url: `/contact`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContactDto,
      signal,
    },
    options,
  );
};

export const getContactControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerCreate>>,
    TError,
    { data: BodyType<CreateContactDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerCreate>>,
  TError,
  { data: BodyType<CreateContactDto> },
  TContext
> => {
  const mutationKey = ["contactControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerCreate>>,
    { data: BodyType<CreateContactDto> }
  > = (props) => {
    const { data } = props ?? {};

    return contactControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerCreate>>
>;
export type ContactControllerCreateMutationBody = BodyType<CreateContactDto>;
export type ContactControllerCreateMutationError = ErrorType<void>;

/**
 * @summary 대출 문의 등록
 */
export const useContactControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerCreate>>,
      TError,
      { data: BodyType<CreateContactDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerCreate>>,
  TError,
  { data: BodyType<CreateContactDto> },
  TContext
> => {
  const mutationOptions = getContactControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 대출 문의 목록 조회
 */
export const contactControllerFindAll = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ContactResponseDto[]>(
    { url: `/contact`, method: "GET", signal },
    options,
  );
};

export const getContactControllerFindAllQueryKey = () => {
  return [`/contact`] as const;
};

export const getContactControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof contactControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getContactControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contactControllerFindAll>>
  > = ({ signal }) => contactControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contactControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContactControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerFindAll>>
>;
export type ContactControllerFindAllQueryError = ErrorType<void>;

export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 대출 문의 목록 조회
 */

export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContactControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 대출 문의 상세 조회
 */
export const contactControllerGetContact = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ContactResponseDto>(
    { url: `/contact/${id}`, method: "GET", signal },
    options,
  );
};

export const getContactControllerGetContactQueryKey = (id: string) => {
  return [`/contact/${id}`] as const;
};

export const getContactControllerGetContactQueryOptions = <
  TData = Awaited<ReturnType<typeof contactControllerGetContact>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerGetContact>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getContactControllerGetContactQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contactControllerGetContact>>
  > = ({ signal }) => contactControllerGetContact(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof contactControllerGetContact>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContactControllerGetContactQueryResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerGetContact>>
>;
export type ContactControllerGetContactQueryError = ErrorType<void>;

export function useContactControllerGetContact<
  TData = Awaited<ReturnType<typeof contactControllerGetContact>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerGetContact>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerGetContact>>,
          TError,
          Awaited<ReturnType<typeof contactControllerGetContact>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerGetContact<
  TData = Awaited<ReturnType<typeof contactControllerGetContact>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerGetContact>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerGetContact>>,
          TError,
          Awaited<ReturnType<typeof contactControllerGetContact>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerGetContact<
  TData = Awaited<ReturnType<typeof contactControllerGetContact>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerGetContact>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 대출 문의 상세 조회
 */

export function useContactControllerGetContact<
  TData = Awaited<ReturnType<typeof contactControllerGetContact>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerGetContact>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContactControllerGetContactQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 대출 문의 삭제
 */
export const contactControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<boolean>(
    { url: `/contact/${id}`, method: "DELETE" },
    options,
  );
};

export const getContactControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["contactControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return contactControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerDelete>>
>;

export type ContactControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary 대출 문의 삭제
 */
export const useContactControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getContactControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 대출 문의 답변 발송
 */
export const contactControllerSendReply = (
  id: string,
  contactReplyDto: BodyType<ContactReplyDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/contact/reply/${id}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: contactReplyDto,
      signal,
    },
    options,
  );
};

export const getContactControllerSendReplyMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerSendReply>>,
    TError,
    { id: string; data: BodyType<ContactReplyDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerSendReply>>,
  TError,
  { id: string; data: BodyType<ContactReplyDto> },
  TContext
> => {
  const mutationKey = ["contactControllerSendReply"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerSendReply>>,
    { id: string; data: BodyType<ContactReplyDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return contactControllerSendReply(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerSendReplyMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerSendReply>>
>;
export type ContactControllerSendReplyMutationBody = BodyType<ContactReplyDto>;
export type ContactControllerSendReplyMutationError = ErrorType<void>;

/**
 * @summary 대출 문의 답변 발송
 */
export const useContactControllerSendReply = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerSendReply>>,
      TError,
      { id: string; data: BodyType<ContactReplyDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerSendReply>>,
  TError,
  { id: string; data: BodyType<ContactReplyDto> },
  TContext
> => {
  const mutationOptions = getContactControllerSendReplyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
