/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { CreateLoanboardDto, LoanboardResponseDto } from "../../const";

import { customInstance } from "../../../shared/axios/lib/customInstance";
import type {
  ErrorType,
  BodyType,
} from "../../../shared/axios/lib/customInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all loan boards
 */
export const loanboardControllerFindAll = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LoanboardResponseDto[]>(
    { url: `/loanboard`, method: "GET", signal },
    options,
  );
};

export const getLoanboardControllerFindAllQueryKey = () => {
  return [`/loanboard`] as const;
};

export const getLoanboardControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof loanboardControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof loanboardControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getLoanboardControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof loanboardControllerFindAll>>
  > = ({ signal }) => loanboardControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof loanboardControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LoanboardControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof loanboardControllerFindAll>>
>;
export type LoanboardControllerFindAllQueryError = ErrorType<unknown>;

export function useLoanboardControllerFindAll<
  TData = Awaited<ReturnType<typeof loanboardControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loanboardControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof loanboardControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLoanboardControllerFindAll<
  TData = Awaited<ReturnType<typeof loanboardControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loanboardControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof loanboardControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLoanboardControllerFindAll<
  TData = Awaited<ReturnType<typeof loanboardControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all loan boards
 */

export function useLoanboardControllerFindAll<
  TData = Awaited<ReturnType<typeof loanboardControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLoanboardControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new loan board
 */
export const loanboardControllerCreate = (
  createLoanboardDto: BodyType<CreateLoanboardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LoanboardResponseDto>(
    {
      url: `/loanboard`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createLoanboardDto,
      signal,
    },
    options,
  );
};

export const getLoanboardControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loanboardControllerCreate>>,
    TError,
    { data: BodyType<CreateLoanboardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loanboardControllerCreate>>,
  TError,
  { data: BodyType<CreateLoanboardDto> },
  TContext
> => {
  const mutationKey = ["loanboardControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loanboardControllerCreate>>,
    { data: BodyType<CreateLoanboardDto> }
  > = (props) => {
    const { data } = props ?? {};

    return loanboardControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoanboardControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof loanboardControllerCreate>>
>;
export type LoanboardControllerCreateMutationBody =
  BodyType<CreateLoanboardDto>;
export type LoanboardControllerCreateMutationError = ErrorType<void>;

/**
 * @summary Create a new loan board
 */
export const useLoanboardControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loanboardControllerCreate>>,
      TError,
      { data: BodyType<CreateLoanboardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loanboardControllerCreate>>,
  TError,
  { data: BodyType<CreateLoanboardDto> },
  TContext
> => {
  const mutationOptions = getLoanboardControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a loan board by ID
 */
export const loanboardControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LoanboardResponseDto>(
    { url: `/loanboard/${id}`, method: "GET", signal },
    options,
  );
};

export const getLoanboardControllerFindOneQueryKey = (id: string) => {
  return [`/loanboard/${id}`] as const;
};

export const getLoanboardControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof loanboardControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getLoanboardControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof loanboardControllerFindOne>>
  > = ({ signal }) => loanboardControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof loanboardControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LoanboardControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof loanboardControllerFindOne>>
>;
export type LoanboardControllerFindOneQueryError = ErrorType<void>;

export function useLoanboardControllerFindOne<
  TData = Awaited<ReturnType<typeof loanboardControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loanboardControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof loanboardControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLoanboardControllerFindOne<
  TData = Awaited<ReturnType<typeof loanboardControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loanboardControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof loanboardControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLoanboardControllerFindOne<
  TData = Awaited<ReturnType<typeof loanboardControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a loan board by ID
 */

export function useLoanboardControllerFindOne<
  TData = Awaited<ReturnType<typeof loanboardControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof loanboardControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLoanboardControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete a loan board by ID
 */
export const loanboardControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/loanboard/${id}`, method: "DELETE" },
    options,
  );
};

export const getLoanboardControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loanboardControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loanboardControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["loanboardControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loanboardControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return loanboardControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoanboardControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof loanboardControllerDelete>>
>;

export type LoanboardControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary Delete a loan board by ID
 */
export const useLoanboardControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loanboardControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loanboardControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getLoanboardControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
