/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * 관리자 역할
 */
export type AdminResponseDtoRole =
  (typeof AdminResponseDtoRole)[keyof typeof AdminResponseDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminResponseDtoRole = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
} as const;
