/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type AdminAccountCreateDto = {
  /** 관리자 계정 ID */
  id: string;
  /** 관리자 계정 비밀번호 */
  password: string;
  /** 관리자 이름 */
  name: string;
};
