/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import type { AdminResponseDtoRole } from "./adminResponseDtoRole";

export type AdminResponseDto = {
  /** 관리자 UUID */
  uuid: string;
  /** 관리자 ID */
  id: string;
  /** 관리자 역할 */
  role: AdminResponseDtoRole;
  /** 생성 시간 */
  createdAt: string;
  /** 수정 시간 */
  updatedAt: string;
};
