/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

export type AdPendingExtendResponseDto = {
  /** 광고 UUID */
  id: string;
  /** 사용자 ID */
  user_id?: string;
  /** 등록 회사 ID */
  company_id: string;
  /** 광고 타입 */
  ad_types?: string[];
  /** 입금자명 */
  deposit_name: string;
  /** 입금 필요 금액 */
  deposit_fee: number;
};
