/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */
import type { AdResponseDtoAdName } from "./adResponseDtoAdName";
import type { AdResponseDtoLoanAvailableLocationItem } from "./adResponseDtoLoanAvailableLocationItem";
import type { AdResponseDtoProductTypeItem } from "./adResponseDtoProductTypeItem";
import type { AdResponseDtoPendingUpdateData } from "./adResponseDtoPendingUpdateData";
import type { CompanyResponseDto } from "./companyResponseDto";
import type { UserResponseDto } from "./userResponseDto";

export type AdResponseDto = {
  /** 광고 ID */
  id: string;
  /** 사용자 ID */
  user_id: string;
  /** 광고 그룹 ID */
  group_id: string;
  /** 광고 유형 */
  ad_name: AdResponseDtoAdName;
  /** 광고 제목 */
  title?: string;
  /** 광고 부제목 */
  sub_title?: string;
  /** 광고 내용 */
  contents?: string;
  /** 이미지 URL */
  image_url?: string;
  /** 대출 가능 지역 */
  loan_available_location?: AdResponseDtoLoanAvailableLocationItem[];
  /** 커버 이미지 */
  cover_img?: string;
  /** 대출 한도 */
  loan_limit?: number;
  /** 광고 표시 위치 */
  ad_present_location?: string;
  /** 상품 유형 */
  product_type?: AdResponseDtoProductTypeItem[];
  /** 남은 횟수 */
  remain: number;
  /** 광고 만료일 */
  ad_present_expire_date?: string;
  /** 생성일 */
  created_at: string;
  /** 수정일 */
  updated_at: string;
  /** 삭제일 */
  deleted_at?: string;
  /** 삭제 여부 */
  deleted: boolean;
  /** 승인 여부 */
  isApproved: boolean;
  /** 거절 여부 */
  isRejected: boolean;
  /** 날짜 연장 대기 여부 */
  isDateExtendPending: boolean;
  /** 횟수 연장 대기 여부 */
  isCountExtendPending: boolean;
  /** 대기 중인 연장 횟수 */
  pendingExtendCount?: number;
  /** 대기 중인 업데이트 데이터 */
  pendingUpdateData?: AdResponseDtoPendingUpdateData;
  /** 업데이트 대기 여부 */
  isUpdatePending: boolean;
  /** 입금자명 */
  deposit_name?: string;
  /** 상품별 입금 필요 금액 */
  deposit_fee?: number;
  /** 등록한 회사 ID */
  company_id: string;
  /** 줄광고 ID */
  scroll_ad_id?: string;
  /** 총 페이지 수 */
  totalPage?: number;
  /** 등록한 회사 정보 */
  company: CompanyResponseDto;
  /** 등록한 사용자 정보 */
  user: UserResponseDto;
};
