/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type AdvertiseControllerRequestDateExtendParams = {
  deposit_name: string;
};
