/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type AdvertiseControllerFindAllofMyAdsParams = {
  user_id: string;
};
