/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type CompanyResponseDto = {
  /** 제목 */
  title: string;
  /** 월 이자율 */
  monthlyInterestRate: string;
  /** 연 이자율 */
  yearlyInterestRate?: string;
  /** 연체 이자율 */
  delinquentInterestRate?: string;
  /** 대출 한도 */
  loanLimit: number;
  /** 추가 비용 */
  additionalCost?: string;
  /** 조기 상환 수수료 */
  earlyRepaymentFee?: string;
  /** 상환 방식 */
  repaymentMethod?: string;
  /** 대출 기간 */
  loanPeriod?: string;
  /** 대출 가능 지역 */
  location: string[];
  /** 상세 내용 */
  contents: string;
  /** 생성일 */
  createdAt?: string;
  /** 수정일 */
  updatedAt?: string;
};
