/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

export type ContactResponseDto = {
  /** 문의 아이디 */
  id: string;
  /** 문의 제목 */
  title: string;
  /** 문의 내용 */
  contents: string;
  /** 작성자 이름 */
  author: string;
  /** 연락처 */
  tel: string;
  /** 문의 생성일 */
  createdAt: string;
  /** 문의 수정일 */
  updatedAt?: string;
};
