/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type ContactReplyDto = {
  /** 대출 문의 답변 내용 */
  message: string;
};
