/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of loan board
 */
export type CreateLoanboardDtoType =
  (typeof CreateLoanboardDtoType)[keyof typeof CreateLoanboardDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLoanboardDtoType = {
  신용: "신용",
  담보: "담보",
} as const;
