/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * 광고 타입
 */
export type CreateAdvertisementDtoAdName =
  (typeof CreateAdvertisementDtoAdName)[keyof typeof CreateAdvertisementDtoAdName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAdvertisementDtoAdName = {
  프리미엄_배너광고: "프리미엄 배너광고",
  메인_베너광고: "메인 베너광고",
  메인_TOP_배너광고: "메인 TOP 배너광고",
  스폰서_링크: "스폰서 링크",
  지역_배너광고: "지역 배너광고",
  상품_배너_광고: "상품 배너 광고",
  실시간_대출문의_업체_등록: "실시간 대출문의 업체 등록",
  줄광고: "줄광고",
  줄광고_점프_추가_사용: "줄광고 점프 추가 사용",
} as const;
