/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import type { CreateNoticeDtoType } from "./createNoticeDtoType";

export type CreateNoticeDto = {
  /** 공지사항 제목 */
  title: string;
  /** 공지사항 내용 */
  contents: string;
  /** 공지사항 유형 */
  type: CreateNoticeDtoType;
};
