/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

/**
 * Type of loan board
 */
export type CreateLoanboardDtoType =
  (typeof CreateLoanboardDtoType)[keyof typeof CreateLoanboardDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLoanboardDtoType = {
  신용: "신용",
  담보: "담보",
} as const;
