/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import type { CreateLoanboardDtoType } from "./createLoanboardDtoType";
import type { CreateLoanboardDtoAvailableLocation } from "./createLoanboardDtoAvailableLocation";

export type CreateLoanboardDto = {
  /** Type of loan board */
  type: CreateLoanboardDtoType;
  /** Available location for the loan */
  available_location: CreateLoanboardDtoAvailableLocation;
  /** Desired loan amount */
  desired_amount: number;
  /** Age of the applicant */
  age: number;
  /** Gender of the applicant */
  gender: string;
  /** Telephone number of the applicant */
  tel: string;
  /** Monthly income of the applicant */
  monthly_income: number;
  /** Job status of the applicant */
  job_status: boolean;
  /** Title of the loan board */
  title: string;
  /** Content of the loan board */
  contents: string;
};
