/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Lenders API
 * 대출업체 데이터 조회 API
 * OpenAPI spec version: 0.1.0
 */

export type GetLendersLendersGetParams = {
  /**
   * 대출업체 검색어
   */
  query?: string | null;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지 당 개수
   */
  page_size?: number;
};
