/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Lenders API
 * 대출업체 데이터 조회 API
 * OpenAPI spec version: 0.1.0
 */
import type { LenderDTOPhone } from "./lenderDTOPhone";

export type LenderDTO = {
  /** 고유 ID */
  id: number;
  /** 등록증번호 */
  registration_number: string;
  /** 업체명 */
  name: string;
  /** 유효기간 */
  valid_period: string;
  /** 대표자 */
  ceo: string;
  /** 소재지(도로명) */
  address: string;
  /** 광고용 전화번호 */
  phone?: LenderDTOPhone;
  /** 등록기관 */
  registrar: string;
};
