/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */
import type { LoanboardRelationResponseDtoType } from "./loanboardRelationResponseDtoType";
import type { LoanboardRelationResponseDtoAvailableLocation } from "./loanboardRelationResponseDtoAvailableLocation";
import type { LoanboardRelationResponseDtoGender } from "./loanboardRelationResponseDtoGender";
import type { CompanyResponseDto } from "./companyResponseDto";

export type LoanboardRelationResponseDto = {
  /** Unique identifier of the loan board */
  id: string;
  /** Type of loan */
  type: LoanboardRelationResponseDtoType;
  /** Available location for the loan */
  available_location: LoanboardRelationResponseDtoAvailableLocation;
  /** Desired loan amount */
  desired_amount: number;
  /** Date when the loan board was written */
  writed_date: string;
  /** Age of the applicant */
  age: number;
  /** Gender of the applicant */
  gender: LoanboardRelationResponseDtoGender;
  /** Telephone number of the applicant */
  tel: string;
  /**
   * Monthly income of the applicant
   * @nullable
   */
  monthly_income: string | null;
  /** Job status of the applicant */
  job_status: boolean;
  /** Title of the loan board */
  title: string;
  /** Content of the loan board */
  contents: string;
  /** Creation date of the loan board */
  createdAt: string;
  /** Last update date of the loan board */
  updatedAt: string;
  /** Company information */
  companies: CompanyResponseDto[];
};
