/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of loan
 */
export type LoanboardResponseDtoType =
  (typeof LoanboardResponseDtoType)[keyof typeof LoanboardResponseDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanboardResponseDtoType = {
  신용: "신용",
  담보: "담보",
} as const;
