/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * Gender of the applicant
 */
export type LoanboardResponseDtoGender =
  (typeof LoanboardResponseDtoGender)[keyof typeof LoanboardResponseDtoGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanboardResponseDtoGender = {
  FEMALE: "FEMALE",
  MALE: "MALE",
} as const;
