/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */
import type { LoanboardResponseDtoType } from "./loanboardResponseDtoType";
import type { LoanboardResponseDtoAvailableLocation } from "./loanboardResponseDtoAvailableLocation";
import type { LoanboardResponseDtoGender } from "./loanboardResponseDtoGender";
import type { AdResponseDto } from "./adResponseDto";

export type LoanboardResponseDto = {
  /** Unique identifier of the loan board */
  id: string;
  /** Type of loan */
  type: LoanboardResponseDtoType;
  /** Available location for the loan */
  available_location: LoanboardResponseDtoAvailableLocation;
  /** Desired loan amount */
  desired_amount: number;
  /** Date when the loan board was written */
  writed_date: string;
  /** Age of the applicant */
  age: number;
  /** Gender of the applicant */
  gender: LoanboardResponseDtoGender;
  /** Telephone number of the applicant */
  tel: string;
  /**
   * Monthly income of the applicant
   * @nullable
   */
  monthly_income: number | null;
  /** Job status of the applicant */
  job_status: boolean;
  /** Title of the loan board */
  title: string;
  /** Content of the loan board */
  contents: string;
  /** Creation date of the loan board */
  createdAt: string;
  /** Last update date of the loan board */
  updatedAt: string;
  /** Advertisement information */
  advertisements: AdResponseDto;
};
