/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

/**
 * Gender of the applicant
 */
export type LoanboardRelationResponseDtoGender =
  (typeof LoanboardRelationResponseDtoGender)[keyof typeof LoanboardRelationResponseDtoGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanboardRelationResponseDtoGender = {
  FEMALE: "FEMALE",
  MALE: "MALE",
} as const;
