/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */
import type { NoticeResponseDtoType } from "./noticeResponseDtoType";

export type NoticeResponseDto = {
  /** 공지사항 아이디 */
  id: string;
  /** 공지사항 제목 */
  title: string;
  /** 공지사항 내용 */
  contents: string;
  /** 공지사항 유형 */
  type: NoticeResponseDtoType;
  /** 공지사항 생성일 */
  createdAt: string;
  /** 공지사항 수정일 */
  updatedAt: string;
};
