/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

/**
 * 공지사항 유형
 */
export type NoticeResponseDtoType =
  (typeof NoticeResponseDtoType)[keyof typeof NoticeResponseDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoticeResponseDtoType = {
  important: "important",
  normal: "normal",
} as const;
