/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Lenders API
 * 대출업체 데이터 조회 API
 * OpenAPI spec version: 0.1.0
 */

export type Pagination = {
  /** 페이지 번호 */
  page: number;
  /** 페이지 당 개수 */
  page_size: number;
  /** 총 레코드 수 */
  total_records: number;
  /** 총 페이지 수 */
  total_pages: number;
};
