/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Lenders API
 * 대출업체 데이터 조회 API
 * OpenAPI spec version: 0.1.0
 */
import type { LenderDTO } from "./lenderDTO";
import type { Pagination } from "./pagination";

export type PaginationLenderDTO = {
  data: LenderDTO[];
  pagination: Pagination;
};
