/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */
import type { ScrollAdResponseDtoLoanAvailableLocationItem } from "./scrollAdResponseDtoLoanAvailableLocationItem";
import type { ScrollAdResponseDtoPendingUpdateData } from "./scrollAdResponseDtoPendingUpdateData";

export type ScrollAdResponseDto = {
  /** 줄광고 ID */
  id: string;
  /** 사용자 ID */
  user_id: string;
  /** 광고 그룹 ID */
  group_id: string;
  /** 광고 제목 */
  title: string;
  /** 대출 가능 지역 */
  loan_available_location?: ScrollAdResponseDtoLoanAvailableLocationItem[];
  /** 대출 한도 */
  loan_limit: number;
  /** 광고 만료일 */
  ad_present_expire_date: string;
  /** 입금자명 */
  deposit_name: string;
  /** 상품별 입금 필요 금액 */
  deposit_fee: number;
  /** 점프 횟수 */
  jump_count: number;
  /** 점프 가능 여부 */
  jump_enabled: boolean;
  /** 점프 일자 */
  jump_date: string;
  /** 생성일 */
  created_at: string;
  /** 수정일 */
  updated_at: string;
  /** 삭제일 */
  deleted_at?: string;
  /** 삭제 여부 */
  deleted: boolean;
  /** 승인 여부 */
  isApproved: boolean;
  /** 거절 여부 */
  isRejected: boolean;
  /** 날짜 연장 대기 여부 */
  isDateExtendPending: boolean;
  /** 횟수 연장 대기 여부 */
  isCountExtendPending: boolean;
  /** 대기 중인 연장 횟수 */
  pendingExtendCount?: number;
  /** 대기 중인 업데이트 데이터 */
  pendingUpdateData?: ScrollAdResponseDtoPendingUpdateData;
  /** 업데이트 대기 여부 */
  isUpdatePending: boolean;
  /** 등록한 회사 이름 */
  company_name: string;
  /** 등록한 회사 ID */
  company_id: string;
};
