/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type UpdateAdvertisementDtoLoanAvailableLocationItem =
  (typeof UpdateAdvertisementDtoLoanAvailableLocationItem)[keyof typeof UpdateAdvertisementDtoLoanAvailableLocationItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdvertisementDtoLoanAvailableLocationItem = {
  전체: "전체",
  서울: "서울",
  경기: "경기",
  인천: "인천",
  대전: "대전",
  대구: "대구",
  부산: "부산",
  광주: "광주",
  울산: "울산",
  세종: "세종",
  강원: "강원",
  충북: "충북",
  충남: "충남",
  전북: "전북",
  전남: "전남",
  경북: "경북",
  경남: "경남",
  제주: "제주",
} as const;
