/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

export type UpdateAdvertisementDtoProductTypeItem =
  (typeof UpdateAdvertisementDtoProductTypeItem)[keyof typeof UpdateAdvertisementDtoProductTypeItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdvertisementDtoProductTypeItem = {
  전체: "전체",
  직장인대출: "직장인대출",
  무직자대출: "무직자대출",
  여성대출: "여성대출",
  개인돈대출: "개인돈대출",
  연체자대출: "연체자대출",
  소액대출: "소액대출",
  무방문대출: "무방문대출",
  월변대출: "월변대출",
  당일대출: "당일대출",
  사업자대출: "사업자대출",
  일수대출: "일수대출",
  저신용자대출: "저신용자대출",
  신용대출: "신용대출",
  추가대출: "추가대출",
  자동차대출: "자동차대출",
  부동산대출: "부동산대출",
  "24시대출": "24시대출",
  급전대출: "급전대출",
  일용직대출: "일용직대출",
  프리랜서대출: "프리랜서대출",
  전당포대출: "전당포대출",
  신불자대출: "신불자대출",
  주부대출: "주부대출",
  회생파산대출: "회생파산대출",
  대환대출: "대환대출",
  기타대출: "기타대출",
} as const;
