/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type UploadResponseDto = {
  /** 업로드된 파일의 URL */
  url: string;
};
