/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export type UserRequiredResponseDto = {
  /** 유저 아이디 */
  id: string;
  /** 유저 이름 */
  registeredNumber: string;
  /** 유저 회사명 */
  companyName: string;
  /** 유저 광고전화번호 */
  advertisementTel: string;
  /** 유저 이름 */
  exponentName: string;
  /** 유저 주소 */
  companyLocation: string;
  /** 유저 등록기관 */
  registrar: string;
};
