/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

export type UserRequiredResponseDto = {
  /** 유저 아이디 */
  id: string;
  /** 유저 이름 */
  registeredNumber: string;
  /** 유저 회사명 */
  companyName: string;
  /** 유저 광고전화번호 */
  advertisementTel: string;
  /** 유저 이름 */
  exponentName: string;
  /** 유저 주소 */
  companyLocation: string;
  /** 유저 등록기관 */
  registrar: string;
};
