/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */

export type UserResponseDto = {
  /** 유저 UUID */
  uuid: string;
  /** 유저 아이디 */
  id: string;
  /** 전화번호 */
  tel: string;
  /** 대표자명 */
  exponentName: string;
  /** 등록번호 */
  registeredNumber: string;
  /** 등록기간 시작일 */
  registerPeriodStart: string;
  /** 등록기간 종료일 */
  registerPeriodEnd: string;
  /** 등록자 */
  registrar: string;
  /** 대출등록증 */
  loanRegistrationCertificate?: string;
  /** 사업자등록증 */
  businessRegistrationCertificate?: string;
  /** 광고 연락처 */
  advertisementTel: string;
  /** 회사명 */
  companyName: string;
  /** 회사 연락처 */
  companyTel: string;
  /** 회사 위치 */
  companyLocation: string;
  /** 활성화 여부 */
  isActive: boolean;
  /** 블랙리스트 여부 */
  isBlacklist: boolean;
  /** 탈퇴 요청 여부 */
  isWithdrawalRequested: boolean;
  remainRealTimeLoanInquiryCompanyRegistration?: number;
  remainScrollAdJumpCount?: number;
};
