/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * 지역, 상품 등을 Query를 통해 여러 개를 보낼 때는 콤마(,)로 구분하여 보내주세요. 예시: ?location=서울,부산,대구
 * OpenAPI spec version: 1.0
 */
import type { CompanyCreateDto } from "./companyCreateDto";

export type UserRegisterDto = {
  /** 아이디 */
  id: string;
  /** 비밀번호 */
  password: string;
  /** 전화번호 */
  tel: string;
  /** 대표자명 */
  exponentName: string;
  /** 대부등록번호 */
  registeredNumber: string;
  /** 대출광고전화번호 */
  advertisementTel: string;
  /** 등록유효기간 시작 */
  registerPeriodStart: string;
  /** 등록유효기간 종료 */
  registerPeriodEnd: string;
  /** 등록기관 */
  registrar: string;
  /** 대부업등록증파일 */
  loanRegistrationCertificate: string;
  /** 사옵자등록증파일 */
  businessRegistrationCertificate: string;
  /** 업체명 */
  companyName: string;
  /** 업체연락처 */
  companyTel: string;
  /** 소재지 */
  companyLocation: string;
  company: CompanyCreateDto;
};
