/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Lenders API
 * 대출업체 데이터 조회 API
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationErrorLocItem } from "./validationErrorLocItem";

export type ValidationError = {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
};
